In [ ]:
import pandas as pd

In [ ]:

filename = '/content/electric_vehicles_spec_2025.csv.csv'

import pandas as pd
df = pd.read_csv(filename)

print(df.head())

    brand                model  top_speed_kmh  battery_capacity_kWh  \
0  Abarth     500e Convertible            155                  37.8
1  Abarth       500e Hatchback            155                  37.8
2  Abarth  600e Scorpionissima            200                  50.8
3  Abarth         600e Turismo            200                  50.8
4  Aiways                   U5            150                  60.0

  battery_type  number_of_cells  torque_nm  efficiency_wh_per_km  range_km  \
0  Lithium-ion            192.0      235.0                   156       225
1  Lithium-ion            192.0      235.0                   149       225
2  Lithium-ion            102.0      345.0                   158       280
3  Lithium-ion            102.0      345.0                   158       280
4  Lithium-ion              NaN      310.0                   156       315

   acceleration_0_100_s  ...  towing_capacity_kg cargo_volume_l  seats  \
0                   7.0  ...                 0.0            185      4
1                   7.0  ...                 0.0            185      4
2                   5.9  ...                 0.0            360      5
3                   6.2  ...                 0.0            360      5
4                   7.5  ...                 NaN            496      5

  drivetrain       segment length_mm width_mm  height_mm  car_body_type  \
0        FWD   B - Compact      3673     1683       1518      Hatchback
1        FWD   B - Compact      3673     1683       1518      Hatchback
2        FWD  JB - Compact      4187     1779       1557            SUV
3        FWD  JB - Compact      4187     1779       1557            SUV
4        FWD   JC - Medium      4680     1865       1700            SUV

                                          source_url
0  https://ev-database.org/car/1904/Abarth-500e-C...
1  https://ev-database.org/car/1903/Abarth-500e-H...
2  https://ev-database.org/car/3057/Abarth-600e-S...
3  https://ev-database.org/car/3056/Abarth-600e-T...
4         https://ev-database.org/car/1678/Aiways-U5

[5 rows x 22 columns]

In [ ]:
df_copy= df.copy()

In [ ]:
df_copy,display()

(       brand                    model  top_speed_kmh  battery_capacity_kWh  \
 0     Abarth         500e Convertible            155                  37.8
 1     Abarth           500e Hatchback            155                  37.8
 2     Abarth      600e Scorpionissima            200                  50.8
 3     Abarth             600e Turismo            200                  50.8
 4     Aiways                       U5            150                  60.0
 ..       ...                      ...            ...                   ...
 473    Zeekr           7X Premium RWD            210                  71.0
 474    Zeekr        X Core RWD (MY25)            190                  49.0
 475    Zeekr  X Long Range RWD (MY25)            190                  65.0
 476    Zeekr   X Privilege AWD (MY25)            190                  65.0
 477  firefly                      NaN            150                  41.2

     battery_type  number_of_cells  torque_nm  efficiency_wh_per_km  range_km  \
 0    Lithium-ion            192.0      235.0                   156       225
 1    Lithium-ion            192.0      235.0                   149       225
 2    Lithium-ion            102.0      345.0                   158       280
 3    Lithium-ion            102.0      345.0                   158       280
 4    Lithium-ion              NaN      310.0                   156       315
 ..           ...              ...        ...                   ...       ...
 473  Lithium-ion              NaN      440.0                   148       365
 474  Lithium-ion              NaN      343.0                   148       265
 475  Lithium-ion              NaN      343.0                   146       360
 476  Lithium-ion              NaN      543.0                   153       350
 477  Lithium-ion            112.0      200.0                   125       250

      acceleration_0_100_s  ...  towing_capacity_kg cargo_volume_l  seats  \
 0                     7.0  ...                 0.0            185      4
 1                     7.0  ...                 0.0            185      4
 2                     5.9  ...                 0.0            360      5
 3                     6.2  ...                 0.0            360      5
 4                     7.5  ...                 NaN            496      5
 ..                    ...  ...                 ...            ...    ...
 473                   6.0  ...              2000.0            539      5
 474                   5.9  ...              1600.0            362      5
 475                   5.6  ...              1600.0            362      5
 476                   3.8  ...              1600.0            362      5
 477                   8.1  ...                 0.0            404      5

     drivetrain       segment length_mm width_mm  height_mm  car_body_type  \
 0          FWD   B - Compact      3673     1683       1518      Hatchback
 1          FWD   B - Compact      3673     1683       1518      Hatchback
 2          FWD  JB - Compact      4187     1779       1557            SUV
 3          FWD  JB - Compact      4187     1779       1557            SUV
 4          FWD   JC - Medium      4680     1865       1700            SUV
 ..         ...           ...       ...      ...        ...            ...
 473        RWD    JD - Large      4787     1930       1650            SUV
 474        RWD  JB - Compact      4432     1836       1566            SUV
 475        RWD  JB - Compact      4432     1836       1566            SUV
 476        AWD  JB - Compact      4432     1836       1566            SUV
 477        RWD   B - Compact      4003     1885       1557      Hatchback

                                             source_url
 0    https://ev-database.org/car/1904/Abarth-500e-C...
 1    https://ev-database.org/car/1903/Abarth-500e-H...
 2    https://ev-database.org/car/3057/Abarth-600e-S...
 3    https://ev-database.org/car/3056/Abarth-600e-T...
 4           https://ev-database.org/car/1678/Aiways-U5
 ..                                                 ...
 473  https://ev-database.org/car/3081/Zeekr-7X-Prem...
 474  https://ev-database.org/car/3197/Zeekr-X-Core-RWD
 475  https://ev-database.org/car/3198/Zeekr-X-Long-...
 476  https://ev-database.org/car/3199/Zeekr-X-Privi...
 477   https://ev-database.org/car/3178/firefly-firefly

 [478 rows x 22 columns],
 None)

In [ ]:
df_copy.describe()

,top_speed_kmh,battery_capacity_kWh,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,fast_charging_power_kw_dc,towing_capacity_kg,seats,length_mm,width_mm,height_mm
count,478.000000,478.000000,276.000000,471.000000,478.000000,478.000000,478.000000,477.000000,452.000000,478.000000,478.000000,478.000000,478.000000
mean,185.487448,74.043724,485.293478,498.012739,162.903766,393.179916,6.882636,125.008386,1052.261062,5.263598,4678.506276,1887.359833,1601.125523
std,34.252773,20.331058,1210.819733,241.461128,34.317532,103.287335,2.730696,58.205012,737.851774,1.003961,369.210573,73.656807,130.754851
min,125.000000,21.300000,72.000000,113.000000,109.000000,135.000000,2.200000,29.000000,0.000000,2.000000,3620.000000,1610.000000,1329.000000
25%,160.000000,60.000000,150.000000,305.000000,143.000000,320.000000,4.800000,80.000000,500.000000,5.000000,4440.000000,1849.000000,1514.000000
50%,180.000000,76.150000,216.000000,430.000000,155.000000,397.500000,6.600000,113.000000,1000.000000,5.000000,4720.000000,1890.000000,1596.000000
75%,201.000000,90.600000,324.000000,679.000000,177.750000,470.000000,8.200000,150.000000,1600.000000,5.000000,4961.000000,1939.000000,1665.000000
max,325.000000,118.000000,7920.000000,1350.000000,370.000000,685.000000,19.100000,281.000000,2500.000000,9.000000,5908.000000,2080.000000,1986.000000

In [ ]:
df_copy.columns

Index(['brand', 'model', 'top_speed_kmh', 'battery_capacity_kWh',
       'battery_type', 'number_of_cells', 'torque_nm', 'efficiency_wh_per_km',
       'range_km', 'acceleration_0_100_s', 'fast_charging_power_kw_dc',
       'fast_charge_port', 'towing_capacity_kg', 'cargo_volume_l', 'seats',
       'drivetrain', 'segment', 'length_mm', 'width_mm', 'height_mm',
       'car_body_type', 'source_url'],
      dtype='object')

In [ ]:
df_copy.dtypes

brand                         object
model                         object
top_speed_kmh                  int64
battery_capacity_kWh         float64
battery_type                  object
number_of_cells              float64
torque_nm                    float64
efficiency_wh_per_km           int64
range_km                       int64
acceleration_0_100_s         float64
fast_charging_power_kw_dc    float64
fast_charge_port              object
towing_capacity_kg           float64
cargo_volume_l                object
seats                          int64
drivetrain                    object
segment                       object
length_mm                      int64
width_mm                       int64
height_mm                      int64
car_body_type                 object
source_url                    object
dtype: object

In [ ]:
df_copy.duplicated().sum()

np.int64(0)

In [ ]:
df_copy.isnull()

,brand,model,top_speed_kmh,battery_capacity_kWh,battery_type,number_of_cells,torque_nm,efficiency_wh_per_km,range_km,acceleration_0_100_s,...,towing_capacity_kg,cargo_volume_l,seats,drivetrain,segment,length_mm,width_mm,height_mm,car_body_type,source_url
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
474,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
475,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
476,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
477,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_copy.isnull().sum()

brand                          0
model                          1
top_speed_kmh                  0
battery_capacity_kWh           0
battery_type                   0
number_of_cells              202
torque_nm                      7
efficiency_wh_per_km           0
range_km                       0
acceleration_0_100_s           0
fast_charging_power_kw_dc      1
fast_charge_port               1
towing_capacity_kg            26
cargo_volume_l                 1
seats                          0
drivetrain                     0
segment                        0
length_mm                      0
width_mm                       0
height_mm                      0
car_body_type                  0
source_url                     0
dtype: int64

In [ ]:
af=[]

In [ ]:
af=df_copy.isnull().sum()

In [ ]:
print(af)

brand                          0
model                          1
top_speed_kmh                  0
battery_capacity_kWh           0
battery_type                   0
number_of_cells              202
torque_nm                      7
efficiency_wh_per_km           0
range_km                       0
acceleration_0_100_s           0
fast_charging_power_kw_dc      1
fast_charge_port               1
towing_capacity_kg            26
cargo_volume_l                 1
seats                          0
drivetrain                     0
segment                        0
length_mm                      0
width_mm                       0
height_mm                      0
car_body_type                  0
source_url                     0
dtype: int64

In [ ]:
columns_with_null_counts = af[af > 0]
print(columns_with_null_counts)

model                          1
number_of_cells              202
torque_nm                      7
fast_charging_power_kw_dc      1
fast_charge_port               1
towing_capacity_kg            26
cargo_volume_l                 1
dtype: int64

In [ ]:
pip install sweetviz

Requirement already satisfied: sweetviz in /usr/local/lib/python3.11/dist-packages (2.3.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (1.24.0)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (1.15.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)

In [ ]:
import sweetviz as sv

In [ ]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.24.0)

In [ ]:
df_copy_c=df_copy['model'].replace(' ','null')

In [ ]:

df_copy = df_copy.fillna('null')

print(df_copy.isnull().sum())

brand                        0
model                        0
top_speed_kmh                0
battery_capacity_kWh         0
battery_type                 0
number_of_cells              0
torque_nm                    0
efficiency_wh_per_km         0
range_km                     0
acceleration_0_100_s         0
fast_charging_power_kw_dc    0
fast_charge_port             0
towing_capacity_kg           0
cargo_volume_l               0
seats                        0
drivetrain                   0
segment                      0
length_mm                    0
width_mm                     0
height_mm                    0
car_body_type                0
source_url                   0
dtype: int64

In [ ]:
df_copy.to_excel('cleaned_data_ev_cars.xlsx', index=False)